' MSE2 Shared Cloud - Silent Launcher
' Does git pull, name prompt, injects creator name, and launches MSE2 invisibly.

Set objShell = CreateObject("WScript.Shell")
Set objFSO = CreateObject("Scripting.FileSystemObject")

strDir = objFSO.GetParentFolderName(WScript.ScriptFullName)
strGit = strDir & "\mingit\cmd\git.exe"
strNode = ""
strConfigFile = strDir & "\creator.txt"
strCustomScript = strDir & "\MSE2\data\magic.mse-game\custom_script"

' ---- Find Node.js ----
Dim nodePaths(2)
nodePaths(0) = "C:\Program Files\nodejs\node.exe"
nodePaths(1) = "C:\Program Files (x86)\nodejs\node.exe"
nodePaths(2) = objShell.ExpandEnvironmentStrings("%APPDATA%") & "\nvm\current\node.exe"
Dim i
For i = 0 To 2
    If objFSO.FileExists(nodePaths(i)) Then
        strNode = nodePaths(i)
        Exit For
    End If
Next

' ---- Git pull (silent, no-rebase) ----
objShell.Environment("PROCESS")("GIT_TERMINAL_PROMPT") = "0"
objShell.Run """" & strGit & """ -C """ & strDir & """ config pull.rebase false", 0, True
objShell.Run """" & strGit & """ -C """ & strDir & """ pull origin main", 0, True

' ---- First launch: ask for name/initials ----
If Not objFSO.FileExists(strConfigFile) Then
    strName = InputBox("Welcome to MTG Card Editor - Shared Cloud!" & vbCrLf & vbCrLf & _
                       "Enter your initials or name." & vbCrLf & _
                       "This will auto-fill the 'By' column on every card you create.", _
                       "Who are you?", "")
    If Trim(strName) = "" Then strName = "?"
    Set f = objFSO.CreateTextFile(strConfigFile, True)
    f.Write Trim(strName)
    f.Close
End If

' ---- Read creator name ----
Set f = objFSO.OpenTextFile(strConfigFile, 1)
strCreator = Trim(f.ReadAll)
f.Close

' ---- Inject creator name into MSE2 custom_script so it auto-fills the By field ----
Set f = objFSO.CreateTextFile(strCustomScript, True)
f.WriteLine "## Auto-generated by launcher - do not edit manually"
f.WriteLine "## Your name is stored in creator.txt next to this app"
f.WriteLine ""
f.WriteLine "creator_name := """ & strCreator & """"
f.WriteLine ""
f.WriteLine "example_script_so_it_doesnt_die := {""""}"
f.Close

' ---- Start Sync Engine silently (if node exists) ----
If strNode <> "" Then
    objShell.Run """" & strNode & """ """ & strDir & "\SyncEngine\sync_engine.js""", 0, False
End If

' ---- Compile MenuAddon.exe if missing (uses .NET Framework built into Windows) ----
Dim cscPath
Dim cscCandidates(1)
cscCandidates(0) = "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
cscCandidates(1) = "C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe"
For i = 0 To 1
    If objFSO.FileExists(cscCandidates(i)) Then cscPath = cscCandidates(i)
Next
If cscPath <> "" And Not objFSO.FileExists(strDir & "\MenuAddon.exe") Then
    objShell.Run """" & cscPath & """ /nologo /r:System.Windows.Forms.dll /out:""" & strDir & "\MenuAddon.exe"" """ & strDir & "\MenuAddon.cs""", 0, True
End If

' ---- Start Menu Addon (adds Account Settings to MSE2 menu bar) ----
objShell.Run """" & strDir & "\MenuAddon.exe"" """ & strDir & "\Settings.vbs""", 0, False

' ---- Launch MSE2 ----
objShell.Run """" & strDir & "\MSE2\magicseteditor.exe""", 1, False
