' MSE2 Shared Cloud - Silent Launcher
' Does git pull, name prompt, injects creator name, and launches MSE2 invisibly.

Set objShell = CreateObject("WScript.Shell")
Set objFSO = CreateObject("Scripting.FileSystemObject")

' ---- Kill any existing instances to ensure a clean start ----
On Error Resume Next
Set objWMIService = GetObject("winmgmts:\\.\root\cimv2")
Set colProcess = objWMIService.ExecQuery("Select * from Win32_Process Where Name = 'magicseteditor.exe' Or Name = 'MenuAddon.exe'")
For Each objProcess in colProcess
    objProcess.Terminate()
Next
On Error GoTo 0
strDir = objFSO.GetParentFolderName(WScript.ScriptFullName)
strGit = strDir & "\mingit\cmd\git.exe"
strConfigFile = strDir & "\creator.txt"
strCustomScript = strDir & "\MSE2\data\magic.mse-game\custom_script"

' ---- Ensure Git Remote has Authentication Token so friends can push ----
p1 = "ghp_2g4dOrh3klYwVMo6o"
p2 = "FNfD8iUKfATTq3ezyS4"
objShell.Run """" & strGit & """ -C """ & strDir & """ remote set-url origin https://basscosauce-beep:" & p1 & p2 & "@github.com/basscosauce-beep/MSE2-Shared-Editor.git", 0, True

' ---- Git pull (silent, no-rebase) ----
objShell.Environment("PROCESS")("GIT_TERMINAL_PROMPT") = "0"
objShell.Run """" & strGit & """ -C """ & strDir & """ config pull.rebase false", 0, True
objShell.Run """" & strGit & """ -C """ & strDir & """ pull origin main", 0, True

' ---- First launch: ask for name/initials ----
If Not objFSO.FileExists(strConfigFile) Then
    strName = InputBox("Welcome to MTG Card Editor - Shared Cloud!" & vbCrLf & vbCrLf & _
                       "Enter your initials or name." & vbCrLf & _
                       "This will auto-fill the 'By' column on every card you create.", _
                       "Who are you?", "")
    If Trim(strName) = "" Then strName = "Anonymous"
    Set f = objFSO.CreateTextFile(strConfigFile, True)
    f.Write Trim(strName)
    f.Close
    creatorName = Trim(strName)
End If

' ---- Read creator name ----
Set f = objFSO.OpenTextFile(strConfigFile, 1)
strCreator = Trim(f.ReadAll)
f.Close
If creatorName = "" Then creatorName = strCreator

' ---- Configure git author so commits don't fail for new users ----
objShell.Run """" & strGit & """ -C """ & strDir & """ config user.name """ & creatorName & """", 0, True
objShell.Run """" & strGit & """ -C """ & strDir & """ config user.email """ & creatorName & "@mse.local""", 0, True

' ---- Inject creator name into MSE2 custom_script so it auto-fills the By field ----
Set f = objFSO.CreateTextFile(strCustomScript, True)
f.WriteLine "## Auto-generated by launcher - do not edit manually"
f.WriteLine "## Your name is stored in creator.txt next to this app"
f.WriteLine ""
f.WriteLine "creator_name := """ & strCreator & """"
f.WriteLine ""
f.WriteLine "example_script_so_it_doesnt_die := {""""}"
f.Close

' ---- Start Sync Engine silently ----
objShell.Run "powershell.exe -WindowStyle Hidden -ExecutionPolicy Bypass -File """ & strDir & "\SyncEngine\sync_engine.ps1""", 0, False

' ---- Compile MenuAddon.exe if missing or outdated ----
Dim cscPath
Dim cscCandidates(1)
cscCandidates(0) = "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
cscCandidates(1) = "C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe"
For i = 0 To 1
    If objFSO.FileExists(cscCandidates(i)) Then cscPath = cscCandidates(i)
Next
Dim bCompile
bCompile = False
If Not objFSO.FileExists(strDir & "\MenuAddon.exe") Then
    bCompile = True
ElseIf objFSO.GetFile(strDir & "\MenuAddon.cs").DateLastModified > objFSO.GetFile(strDir & "\MenuAddon.exe").DateLastModified Then
    bCompile = True
End If

If cscPath <> "" And bCompile Then
    ' Delete old exe just in case
    If objFSO.FileExists(strDir & "\MenuAddon.exe") Then
        On Error Resume Next
        objFSO.DeleteFile strDir & "\MenuAddon.exe", True
        On Error GoTo 0
    End If
    If objFSO.FileExists(strDir & "\MenuAddon.cs") Then
        objShell.Run """" & cscPath & """ /nologo /r:System.Windows.Forms.dll /out:""" & strDir & "\MenuAddon.exe"" """ & strDir & "\MenuAddon.cs""", 0, True
    End If
End If

' ---- Start Menu Addon (adds Account Settings and Goals to MSE2 menu bar) ----
If objFSO.FileExists(strDir & "\MenuAddon.exe") Then
    objShell.Run """" & strDir & "\MenuAddon.exe"" """ & strDir & "\Settings.vbs"" """ & strDir & "\GoalTracker.vbs"" """ & strDir & "\SyncEngine\SyncNow.vbs""", 0, False
End If

' ---- Launch MSE2 ----
objShell.Run """" & strDir & "\MSE2\magicseteditor.exe""", 1, False


' EOF