Add-Type -AssemblyName PresentationFramework
Add-Type -AssemblyName PresentationCore
Add-Type -AssemblyName WindowsBase

$installDir = [System.Environment]::GetFolderPath("LocalApplicationData") + "\MSE2_Shared_Cloud"
$creatorFile = "$installDir\creator.txt"
$customScript = "$installDir\MSE2\data\magic.mse-game\custom_script"

# Read current name
$currentName = ""
if (Test-Path $creatorFile) {
    $currentName = (Get-Content $creatorFile -Raw).Trim()
}

# Build the WPF window
[xml]$xaml = @"
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="Account Settings" Height="220" Width="380"
        WindowStartupLocation="CenterScreen" ResizeMode="NoResize"
        Background="#1a1a2e">
    <Window.Resources>
        <Style TargetType="Button">
            <Setter Property="Background" Value="#7b2d8b"/>
            <Setter Property="Foreground" Value="White"/>
            <Setter Property="BorderThickness" Value="0"/>
            <Setter Property="Padding" Value="16,8"/>
            <Setter Property="FontSize" Value="13"/>
            <Setter Property="FontFamily" Value="Segoe UI"/>
            <Setter Property="Cursor" Value="Hand"/>
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="Button">
                        <Border Background="{TemplateBinding Background}" CornerRadius="6" Padding="{TemplateBinding Padding}">
                            <ContentPresenter HorizontalAlignment="Center" VerticalAlignment="Center"/>
                        </Border>
                        <ControlTemplate.Triggers>
                            <Trigger Property="IsMouseOver" Value="True">
                                <Setter Property="Background" Value="#9b3dab"/>
                            </Trigger>
                        </ControlTemplate.Triggers>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
    </Window.Resources>
    <StackPanel Margin="30,24,30,24">
        <TextBlock Text="MTG Card Editor" FontSize="11" Foreground="#888" FontFamily="Segoe UI" Margin="0,0,0,2"/>
        <TextBlock Text="Account Settings" FontSize="20" FontWeight="Bold" Foreground="White" FontFamily="Segoe UI" Margin="0,0,0,20"/>
        <TextBlock Text="Your name / initials" FontSize="12" Foreground="#aaa" FontFamily="Segoe UI" Margin="0,0,0,6"/>
        <Border Background="#16213e" CornerRadius="6" Padding="2">
            <TextBox x:Name="NameBox" Text="$currentName" FontSize="14" FontFamily="Segoe UI"
                     Background="Transparent" Foreground="White" BorderThickness="0"
                     Padding="10,8" CaretBrush="White" SelectionBrush="#7b2d8b"/>
        </Border>
        <TextBlock x:Name="StatusText" Text="" FontSize="11" Foreground="#4ecca3" FontFamily="Segoe UI" Margin="0,8,0,0" Height="18"/>
        <StackPanel Orientation="Horizontal" HorizontalAlignment="Right" Margin="0,10,0,0">
            <Button x:Name="CancelBtn" Content="Cancel" Background="#333" Margin="0,0,10,0"/>
            <Button x:Name="SaveBtn" Content="Save Changes"/>
        </StackPanel>
    </StackPanel>
</Window>
"@

$reader = New-Object System.Xml.XmlNodeReader $xaml
$window = [Windows.Markup.XamlReader]::Load($reader)

$nameBox    = $window.FindName("NameBox")
$saveBtn    = $window.FindName("SaveBtn")
$cancelBtn  = $window.FindName("CancelBtn")
$statusText = $window.FindName("StatusText")

$nameBox.SelectAll()

$saveBtn.Add_Click({
    $newName = $nameBox.Text.Trim()
    if ($newName -eq "") { $newName = "?" }

    # Save to creator.txt
    Set-Content $creatorFile $newName -NoNewline

    # Update custom_script
    $scriptContent = "## Auto-generated by launcher - do not edit manually`r`n## Your name is stored in creator.txt next to this app`r`n`r`ncreator_name := `"$newName`"`r`n`r`nexample_script_so_it_doesnt_die := {`"`"}"
    Set-Content $customScript $scriptContent -NoNewline

    $statusText.Text = "Saved! Restart MSE2 for changes to take effect."
    $saveBtn.IsEnabled = $false
})

$cancelBtn.Add_Click({ $window.Close() })

$window.ShowDialog() | Out-Null
